### ISSUE TITLE
What's required to make TS find the types here?

### ISSUE THREAD

**Issue by prewk** [babangsund/cypress-keycloak#12]
Hi!

I'm fighting a bit here with making TS (Using WebStorm) actually accept the types for this great package:

![image](https://user-images.githubusercontent.com/640102/116227132-15d05b80-a754-11eb-8a06-128232fcd3e5.png)

Reading cypress' help on Typescript doesn't really say anything about third-party packages like this, it just talks about how to type your own commands.

Can you help me? Thanks a lot!

**Comment by nerumo** [comment]
It seams that the index.d.ts isn't specified in the package.json


Missing piece here:
```
  "types": "src/index.d.ts",
```

**Comment by prewk** [comment]
Thanks a bunch @nerumo!

#13
