### ISSUE TITLE
Docs and Types Mismatch

### ISSUE THREAD

**Issue by eccentric-j** [babangsund/cypress-keycloak#17]
In the Readme https://github.com/babangsund/cypress-keycloak/blob/edc34e705bb28ace5f40801f9620f435cd4860c3/README.md

It shows:

```
cy.logout({ ... }):
  root: string
  realm: string
  redirect_uri: string
  path_prefix?: string = "auth"
```

But in the index.d.ts file:
https://github.com/babangsund/cypress-keycloak/blob/edc34e705bb28ace5f40801f9620f435cd4860c3/src/index.d.ts#L1-L8

The logout method does not accept a path_prefix. Happy to contribute a PR but what is the source of truth here?

**Comment by babangsund** [comment]
The source of truth is [here](https://github.com/babangsund/cypress-keycloak/blob/master/src/logout.ts).

Feel free to open a PR!
