### ISSUE TITLE
handling of redirect_uri with keycloak 18 during logout

### ISSUE THREAD

**Issue by d-koppenhagen** [babangsund/cypress-keycloak#29]
Keycloak 18 will not handle the `redirect_uri` param anymore which is used [here](https://github.com/babangsund/cypress-keycloak/blob/master/src/logout.ts).

The Breaking Change in Keycloak is described in the [Release Notes](https://www.keycloak.org/2022/04/keycloak-1800-released) - Section "Migration from 17.0 -> OpenID Connect Logout".

The params `post_logout_redirect_uri` together with the parameter `id_token_hint` should be handled.

**Comment by szabolcs-dekany** [comment]
Would be great if this PR could be merged. Just ran into this issue after upgrading our Keycloak to the latest version
