### ISSUE TITLE
Peer dependency for Cypress 11

### ISSUE THREAD

**Issue by bakgaard** [babangsund/cypress-keycloak#46]
Can we have `peerDependencies` include version 11 of Cypress?

```json
"peerDependencies": {
    "cypress": "^6.5.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0" # Right here
  },
```

**Comment by Gardosen** [comment]
I would either suggest to drop the peerDependencies. 

whoever still uses cypress below 6, probably does not even use keycloak. adding more and more major cypress versions is prolonging the list in a way which seems redundant. as every version is supported seemingly. I use cypress-keycloak without issues with cypress 11.2

**Comment by bakgaard** [comment]
I can make an `overwrite` in my package.json, or `npm i --force`. Do you have an alternative?

**Comment by rstens** [comment]
These dependencies have tripped me up a few times already, I second dropping.

**Comment by babangsund** [comment]
Closed by https://github.com/babangsund/cypress-keycloak/pull/52
