### ISSUE TITLE
Peer dependency for Cypress 12

### ISSUE THREAD

**Issue by marousis** [babangsund/cypress-keycloak#48]
Please add peer dependency for Cypress 12

Now is:
`"peerDependencies": {
    "cypress": "^6.5.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0"
  }`

Should be:
`"peerDependencies": {
    "cypress": "^6.5.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0"
  }`

**Comment by alecmestroni** [comment]
same here, agree with him

**Comment by marlonkerstens** [comment]
Also need this! 🙏

**Comment by githubaja** [comment]
I can confirm this. 
Here is the full error stack:

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress10@1.0.0
npm ERR! Found: cypress@12.3.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^12.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^6.5.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0" from cypress-keycloak@2.0.0
npm ERR! node_modules/cypress-keycloak
npm ERR!   dev cypress-keycloak@"^2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by alex-w0** [comment]
Is this repo still maintained?
