### ISSUE TITLE
Login doesn't seem to work with referenced values

### ISSUE THREAD

**Issue by jameseg** [babangsund/cypress-keycloak#7]
I'm trying to hide my credentials using https://github.com/bahmutov/as-a

If I use the `login()` method, passing my credentials in to the `username` and `password` fields, everything works just fine.

But when I try to reference those same exact same values by using `Cypress.env('username')` and `Cypress.env('password`) - the authentication fails everytime.

I've tried `toString()` and `encodeURI()` but to no avail.  Any ideas are welcome!

**Comment by babangsund** [comment]
Stale, closing.
